version: "3.8"

services:
  rabbitmq:
    image: docker.io/library/rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Messaging port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  inventory_service:
    build:
      context: ./inventory_service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672

  notification_service:
    build:
      context: ./notification_service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672

  order_service:
    build:
      context: ./order_service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
